module.exports = {
  origin: 'https://miniprogram.default',
  entry: '/',
  domSubTreeLevel: 5,
  elementMultiplexing: true,
  textMultiplexing: true,
  commentMultiplexing: true,
  domExtendMultiplexing: true,
  styleValueReduce: 5000,
  attrValueReduce: 5000,
  navigationStyle: 'custom',
  navigationBarBackgroundColor: '#000000',
  navigationBarTextStyle: 'white',
  backgroundColor: '#FFFFFF',
  backgroundTextStyle: 'dark',
  backgroundColorTop: '#FFFFFF',
  backgroundColorBottom: '#FFFFFF',
  enablePullDownRefresh: false,
  onReachBottomDistance: 50,
  pageOrientation: 'portrait',
  package: require('../../package.json')
}
